-- ============================================================
-- Changeset V007: Create leases table + single active lease
--                 partial unique index (TRD §9.1)
-- Schema  : public
-- Author  : Befiker Gezahegn Hailemichael
-- Purpose : Formal time-bound agreement binding a TenantProfile
--           to a Unit. The foundational object against which the
--           billing engine (Phase 4) will generate invoices.
--
-- Critical constraint:
--   idx_unique_active_lease_per_unit — a partial unique index
--   on (tenant_id, unit_id) WHERE status = 'ACTIVE' enforces
--   the Single Active Lease Rule (TRD §9.1 / PRD v2.1 §5.2).
--   This is a database-level guarantee, not an application check.
--
-- All monetary columns use NUMERIC(15,2) per TRD §4.1.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.leases
(
    id                 UUID           NOT NULL DEFAULT gen_random_uuid(),
    tenant_id          UUID           NOT NULL,
    unit_id            UUID           NOT NULL,
    tenant_profile_id  UUID           NOT NULL,
    status             VARCHAR(30)    NOT NULL DEFAULT 'DRAFT',
    start_date         DATE           NOT NULL,
    end_date           DATE           NOT NULL,
    monthly_rent       NUMERIC(15,2)  NOT NULL,
    billing_day        SMALLINT       NOT NULL DEFAULT 1,
    security_deposit   NUMERIC(15,2)           DEFAULT 0.00,
    escalation_terms   TEXT,
    created_at         TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_leases
        PRIMARY KEY (id),

    CONSTRAINT fk_leases_organization
        FOREIGN KEY (tenant_id)
        REFERENCES public.organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leases_unit
        FOREIGN KEY (unit_id)
        REFERENCES public.units (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_leases_tenant_profile
        FOREIGN KEY (tenant_profile_id)
        REFERENCES public.tenant_profiles (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_leases_status
        CHECK (status IN ('DRAFT', 'PENDING', 'ACTIVE', 'TERMINATED', 'EXPIRED')),

    CONSTRAINT chk_leases_end_after_start
        CHECK (end_date > start_date),

    CONSTRAINT chk_leases_monthly_rent_positive
        CHECK (monthly_rent > 0),

    CONSTRAINT chk_leases_billing_day
        CHECK (billing_day BETWEEN 1 AND 28)
);

-- ============================================================
-- TRD §9.1 — Single Active Lease Constraint
-- Partial unique index: only one ACTIVE lease per unit per org.
-- Historical (TERMINATED, EXPIRED) and future-dated (DRAFT,
-- PENDING) leases for the same unit coexist freely — only
-- simultaneous active tenancy is forbidden.
-- ============================================================
CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_active_lease_per_unit
    ON public.leases (tenant_id, unit_id)
    WHERE status = 'ACTIVE';

CREATE INDEX IF NOT EXISTS idx_leases_tenant_id
    ON public.leases (tenant_id);

CREATE INDEX IF NOT EXISTS idx_leases_unit_id
    ON public.leases (tenant_id, unit_id);

CREATE INDEX IF NOT EXISTS idx_leases_tenant_profile_id
    ON public.leases (tenant_id, tenant_profile_id);

CREATE INDEX IF NOT EXISTS idx_leases_status
    ON public.leases (tenant_id, status);

COMMENT ON TABLE  public.leases                   IS 'Formal time-bound agreement binding a TenantProfile to a Unit.';
COMMENT ON COLUMN public.leases.tenant_id         IS 'FK to organizations(id) — tenant isolation discriminator.';
COMMENT ON COLUMN public.leases.unit_id           IS 'FK to units(id) — ON DELETE RESTRICT.';
COMMENT ON COLUMN public.leases.tenant_profile_id IS 'FK to tenant_profiles(id) — ON DELETE RESTRICT.';
COMMENT ON COLUMN public.leases.status            IS 'Lifecycle: DRAFT → PENDING → ACTIVE → TERMINATED or EXPIRED.';
COMMENT ON COLUMN public.leases.monthly_rent      IS 'NUMERIC(15,2) — locked at signing. Never FLOAT. TRD §4.1.';
COMMENT ON COLUMN public.leases.billing_day       IS 'Day of month (1–28) on which invoices are generated by the billing engine.';
COMMENT ON COLUMN public.leases.security_deposit  IS 'NUMERIC(15,2) security deposit amount. Optional.';