-- ============================================================
-- Changeset V008: Create invoices table
-- Schema  : public
-- Author  : Befiker Gezahegn Hailemichael
-- Purpose : Financial statements generated automatically by the
--           Spring Batch billing engine against active leases.
--
-- Critical constraint (TRD §9.2):
--   uq_invoice_per_lease_period — UNIQUE(lease_id, billing_period)
--   This composite unique index is the database-level guarantee
--   that the billing engine is structurally incapable of generating
--   duplicate invoices for the same lease in the same period.
--   Running the batch job multiple times for the same month is safe.
--
-- All monetary columns use NUMERIC(15,2) per TRD §4.1.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.invoices
(
    id             UUID          NOT NULL DEFAULT gen_random_uuid(),
    tenant_id      UUID          NOT NULL,
    lease_id       UUID          NOT NULL,
    billing_period VARCHAR(7)    NOT NULL,
    amount_due     NUMERIC(15,2) NOT NULL,
    amount_paid    NUMERIC(15,2) NOT NULL DEFAULT 0.00,
    status         VARCHAR(30)   NOT NULL DEFAULT 'UNPAID',
    due_date       DATE          NOT NULL,
    issued_at      TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_invoices
        PRIMARY KEY (id),

    CONSTRAINT fk_invoices_organization
        FOREIGN KEY (tenant_id)
        REFERENCES public.organizations (id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_invoices_lease
        FOREIGN KEY (lease_id)
        REFERENCES public.leases (id)
        ON DELETE RESTRICT,

    CONSTRAINT chk_invoices_status
        CHECK (status IN ('UNPAID', 'PARTIALLY_PAID', 'PAID')),

    CONSTRAINT chk_invoices_amount_due_positive
        CHECK (amount_due > 0),

    CONSTRAINT chk_invoices_amount_paid_non_negative
        CHECK (amount_paid >= 0),

    CONSTRAINT chk_invoices_billing_period_format
        CHECK (billing_period ~ '^\d{4}-(0[1-9]|1[0-2])$')
);

-- ============================================================
-- TRD §9.2 — Billing Idempotency Constraint
-- Composite unique index: one invoice per lease per billing period.
-- Spring Batch InvoiceWriter uses INSERT ... ON CONFLICT DO NOTHING.
-- ============================================================
CREATE UNIQUE INDEX IF NOT EXISTS idx_uq_invoice_per_lease_period
    ON public.invoices (lease_id, billing_period);

CREATE INDEX IF NOT EXISTS idx_invoices_tenant_id
    ON public.invoices (tenant_id);

CREATE INDEX IF NOT EXISTS idx_invoices_tenant_status
    ON public.invoices (tenant_id, status);

CREATE INDEX IF NOT EXISTS idx_invoices_tenant_lease
    ON public.invoices (tenant_id, lease_id);

COMMENT ON TABLE  public.invoices                IS 'Financial statements auto-generated by Spring Batch billing engine.';
COMMENT ON COLUMN public.invoices.billing_period IS 'Format: YYYY-MM. Part of the composite unique index for idempotency.';
COMMENT ON COLUMN public.invoices.amount_due     IS 'NUMERIC(15,2) — snapshot of monthly_rent at generation time. Never FLOAT.';
COMMENT ON COLUMN public.invoices.amount_paid    IS 'NUMERIC(15,2) — running total updated as payments are logged.';
COMMENT ON COLUMN public.invoices.status         IS 'UNPAID → PARTIALLY_PAID → PAID. Auto-transitions on payment logging.';