package com.propmanager.modules.organization.mapper;

import com.propmanager.modules.organization.dto.OrganizationRequestDto;
import com.propmanager.modules.organization.dto.OrganizationResponseDto;
import com.propmanager.modules.organization.entity.Organization;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * MapStruct mapper translating between the Organization JPA entity and its
 * inbound/outbound DTO representations.
 *
 * componentModel = "spring" registers this mapper as a Spring-managed bean,
 * allowing it to be constructor-injected into OrganizationServiceImpl without
 * any manual instantiation.
 *
 * Mapping notes:
 *   - toEntity: the id, status, createdAt, and updatedAt fields are ignored
 *     on the request → entity mapping because they are either generated by
 *     the database (id, timestamps) or defaulted by the entity builder
 *     (status = ACTIVE). Explicitly ignoring them prevents MapStruct from
 *     attempting to map null source values onto those fields.
 *   - toResponseDto: all fields map by name convention — no overrides needed.
 */
@Mapper(componentModel = "spring")
public interface OrganizationMapper {

    @Mapping(target = "id",        ignore = true)
    @Mapping(target = "status",    ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    Organization toEntity(OrganizationRequestDto requestDto);

    OrganizationResponseDto toResponseDto(Organization organization);
}