package com.propmanager.modules.organization.mapper;

import com.propmanager.modules.organization.dto.StaffMemberRequestDto;
import com.propmanager.modules.organization.dto.StaffMemberResponseDto;
import com.propmanager.modules.organization.entity.StaffMember;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * MapStruct mapper for StaffMember ↔ DTO conversions.
 *
 * toEntity mapping notes:
 *   - id, createdAt, updatedAt: ignored — generated by database / Hibernate.
 *   - passwordHash: ignored — set explicitly in StaffMemberServiceImpl
 *     after BCrypt hashing. Never sourced from the DTO.
 *   - tenantId: ignored — sourced from TenantContext in the service layer,
 *     never from the request body.
 *   - status: ignored — defaults to ACTIVE via @Builder.Default on the entity.
 *   - The DTO's `password` field has no corresponding target on StaffMember
 *     (the entity has `passwordHash`, not `password`). MapStruct automatically
 *     ignores unmatched source fields — no explicit ignore needed here.
 *
 * toResponseDto mapping notes:
 *   - All fields map by name convention from entity to DTO.
 */
@Mapper(componentModel = "spring")
public interface StaffMemberMapper {

    @Mapping(target = "id",           ignore = true)
    @Mapping(target = "passwordHash", ignore = true)
    @Mapping(target = "tenantId",     ignore = true)
    @Mapping(target = "status",       ignore = true)
    @Mapping(target = "createdAt",    ignore = true)
    @Mapping(target = "updatedAt",    ignore = true)
    StaffMember toEntity(StaffMemberRequestDto requestDto);

    StaffMemberResponseDto toResponseDto(StaffMember staffMember);
}