DROP TABLE IF EXISTS public.BATCH_STEP_EXECUTION_CONTEXT CASCADE;
DROP TABLE IF EXISTS public.BATCH_JOB_EXECUTION_CONTEXT CASCADE;
DROP TABLE IF EXISTS public.BATCH_STEP_EXECUTION CASCADE;
DROP TABLE IF EXISTS public.BATCH_JOB_EXECUTION_PARAMS CASCADE;
DROP TABLE IF EXISTS public.BATCH_JOB_EXECUTION CASCADE;
DROP TABLE IF EXISTS public.BATCH_JOB_INSTANCE CASCADE;
